### ISSUE TITLE
Package doesn't import

### ISSUE THREAD

**Issue by Amina-Ibm** [shiloSaadon/simple_animated_dialog#1]
![package_error](https://github.com/user-attachments/assets/896d8dac-e8e6-45ad-9001-b59e87175938)

- Added an error screenshot.
- The dependency is added to .yaml file. 
- I ran pub get and pub upgrade too

**Comment by shiloSaadon** [comment]
It seems like you are importing the wrong file.

you need to import that 

```import 'package:simple_animated_dialog/simple_animated_dialog_lib.dart';```

Notice the ```_lib``` at the end.

I have also changed the documentation. Thanks and sorry for the delay ;)
